#!/usr/bin/env bash

set -euxo pipefail

if [[ $# -gt 0 ]]; then
  echo "
  Usage: ${0##*/}
  Builds and installs bspterm onto your system into ~/.local, making it available as ~/.local/bin/bspterm.

  Before running this you should ensure you have all the build dependencies installed with \`./script/linux\`.
  "
  exit 1
fi
export BSPTERM_CHANNEL=$(<crates/bspterm/RELEASE_CHANNEL)
export BSPTERM_UPDATE_EXPLANATION="You need to fetch and rebuild bspterm in $(pwd)"
script/bundle-linux

arch="$(uname -m)"
commit=$(git rev-parse HEAD | cut -c 1-7)
archive="bspterm-linux-${arch}.tar.gz"
export BSPTERM_BUNDLE_PATH="${CARGO_TARGET_DIR:-target}/release/${archive}"
script/install.sh
